#!/bin/sh

log() {
    printf '\033[32m->\033[m %s.\n' "$*"
}

err() {
    log "$*" >&2
    exit 1
}

log --- starting cleanwire ---
log "stopping services (pipewire, wireplumber, pipewire-pulse, dbus)"

rc-service -U pipewire stop 2>/dev/null
rc-service -U wireplumber stop 2>/dev/null
rc-service -U pipewire-pulse stop 2>/dev/null
rc-service -U dbus stop 2>/dev/null

log cleaning pids

rm -rf /home/diego/.cache/xdg-runtime/pulse
rm -f /home/diego/.cache/xdg-runtime/supervise-*.pid

log starting services

rc-service -U dbus start || err dbus not started
rc-service -U pipewire start || err pipewire not started
rc-service -U wireplumber start || err wireplumber not started
rc-service -U pipewire-pulse start || err pipewire-pulse not started 
