#!/bin/sh

efibootmgr -b 0000 -B 2>/dev/null
efibootmgr -b 0001 -B 2>/dev/null

efibootmgr --disk /dev/nvme0n1 \
           --part 1 \
           --create \
           --label "VOIDLINUX" \
           --loader /vmlinuz \
           --unicode "root=UUID=94d59b0a-6e7c-4c0a-80d5-6851bba6e32f initrd=\initramfs ro loglevel=4"

efibootmgr --disk /dev/nvme0n1 \
           --part 1 \
           --create \
           --label "VOIDLINUXOLD" \
           --loader /vmlinuz.old \
           --unicode "root=UUID=94d59b0a-6e7c-4c0a-80d5-6851bba6e32f initrd=\initramfs.old ro loglevel=4"
