#!/bin/sh

[ $1 ] || exit 1

exec mpv \
    --no-audio \
    --loop-file=inf \
    --keep-open=yes \
    --image-display-duration=inf \
    --profile=sw-fast \
    --geometry=50%x50% \
    --autofit-larger=90%x90% \
    --title="mpv-image-viewer" \
    "$@"
