#!/bin/sh

TYPE=$1
PKG=$2
DEST=$3

_current_pkg_file="/tmp/kiss-current-pkg"

if [ "${KISS_COLOR:-1}" != 0 ] && [ -t 2 ]; then
    c1='\033[1;33m'
    c2='\033[1;34m'
    c3='\033[m'
fi

log() {
    printf '%b%s %b%s%b %s\n' \
        "$c1" "->" "${c3}${2:+$c2}" "$1" "$c3" "$2" >&2
}

_timefile=${KISS_TMPDIR:-/tmp}/_kh_start-$PKG

case $TYPE in
    pre-build)
        cat /proc/uptime > "$_timefile" 2>/dev/null
        printf '%s\n' "$PKG" > "$_current_pkg_file"

        case $PKG in
            mesa)
                _flags=-Dgallium-drivers=radeonsi
                _flags=$_flags\ -Dvulkan-drivers=amd
                _flags=$_flags\ -Dvideo-codecs=all

                sed -i "s/\. output/$_flags \0/" .build
            ;;
        esac
    ;;

    post-build)
        rm -f "$_current_pkg_file"

        if [ -f "$_timefile" ]; then
            IFS=. read -r _start _ < "$_timefile"
            IFS=. read -r _end _ < /proc/uptime
            rm -f "$_timefile"

            _s=$((_end - _start))
            _h=$((_s / 60 / 60 % 24))
            _m=$((_s / 60 % 60))

            [ "$_h" = 0 ] || _u="${_u}${_h}h "
            [ "$_m" = 0 ] || _u="${_u}${_m}m "

            log "$PKG" "Build finished in ${_u:-${_s}s}"
        fi

        case $PKG in
           kiss) rm -rf "$DEST/usr/bin" ;;

           *)
               rm -rf "$DEST/usr/share/doc"
               rm -rf "$DEST/usr/share/gettext"
               rm -rf "$DEST/usr/share/man"
               rm -rf "$DEST/usr/share/locale"
               rm -rf "$DEST/usr/share/polkit-1"
               rm -rf "$DEST/usr/share/info"
               rm -rf "$DEST/usr/share/gtk-doc"
               rm -rf "$DEST/usr/share/zsh"
               rm  -f "$DEST/usr/lib/charset.alias"
           ;;
        esac
    ;;
esac
