#!/bin/sh -e
# Shows the current package building 

[ "${KISS_COLOR:-1}" != 0 ] && [ -t 1 ] && {
    c0="$(printf "\033[m")"
    c1="$(printf "\033[1;33m")"
    c2="$(printf "\033[1;34m")"
} || {
    c0=""
    c1=""
    c2=""
}

prompt="${c1}->${c0}"
current="/tmp/_kh_current_pkg"

[ -f "$current" ] && read -r pkg < "$current"

if [ -n "$pkg" ]; then
    printf "${prompt} Current package building: ${c2}%s${c0}\n" "$pkg"
else
    printf "${prompt} No package currently building\n"
    exit 1
fi
