#!/bin/bash
# 
# okwal - pywal wrapper to use okpal as backend for
#         applying the palettes

WAL_COLORS="$HOME/.cache/wal/colors"
PALETTE_DIR="$HOME/.config/okpal/palettes/dark"
TARGET="$PALETTE_DIR/wal"

log() {
    printf '\033[32m->\033[m %s.\n' "$*"
}

err() {
    log "$*" >&2
    exit 1
}

set_wallpaper() {
    local input_file="${1:-$HOME/imagenes/wallpaper.jpg}"
    if [[ ! -f "$input_file" ]]; then
        input_file=$(ls "$HOME"/imagenes/wallpaper.{jpg,png} 2>/dev/null | head -n 1)
        [[ -z "$input_file" ]] && err "no wallpaper found"
    fi
    export WAL="$input_file"
    log "using wallpaper: $WAL"
    wal -i "$WAL" >/dev/null 2>&1
}

generate_palette() {
    [[ -f "$WAL_COLORS" ]] || err "colors file not found at $WAL_COLORS"
    mkdir -p "$PALETTE_DIR" || err "failed to create directory $PALETTE_DIR"
    mapfile -t colors < <(sed 's/#//' "$WAL_COLORS")
    cat <<EOF > "$TARGET"
background=${colors[0]}
foreground=${colors[7]}
cursor=${colors[7]}
color00=${colors[0]}
color01=${colors[1]}
color02=${colors[2]}
color03=${colors[3]}
color04=${colors[4]}
color05=${colors[5]}
color06=${colors[6]}
color07=${colors[7]}
color08=${colors[8]}
color09=${colors[9]}
color10=${colors[10]}
color11=${colors[11]}
color12=${colors[12]}
color13=${colors[13]}
color14=${colors[14]}
color15=${colors[15]}
EOF
}

main() {
	okpal || err okpal not found
	pywal || err pywal not found
        log "starting wal to okpal conversion..."
        set_wallpaper "$1"
        generate_palette
        log "palette successfully generated at $TARGET"
        okpal -s wal >/dev/null 2>&1
        rm -rf $HOME/.cache/wal/schemes
}

main "$@"
