#!/bin/sh

[ "$1" ] || printf "use: pal -h\n"

if [ "$1" = "-l" ]; then
	ls /etc/paleta/palettes
elif [ "$1" = "-s" ]; then
	if [ -f "/etc/paleta/palettes/$2" ]; then
		paleta < /etc/paleta/palettes/$2 > ~/.cache/current-palette
		printf "Using palette: $2\n\n"
		for i in 0 1 2 3 4 5 6 7; do
			printf '\033[4%sm  \033[m' "$i"
		done

		printf "\n"

		for i in 0 1 2 3 4 5 6 7; do
			printf '\033[10%sm  \033[m' "$i"
		done

		printf "\n"
	else
		printf "error: palette does not exist\n"
		exit 1
	fi
elif [ "$1" = "-h" ]; then
	printf "usage: pal [-s palette|-l]\n"
	printf "\n"
	printf "-s palette  Select a palette\n"
	printf "-l          List all palettes\n"
	printf "-h          Show this information\n"
fi
