#!/bin/bash

full() {
	grim -t png -c - | tee /home/diego/imagenes/capturas/screenshot-$(date +%Y%m%d-%H%M%S).png | wl-copy -t image/png
}

geometry() {
	grim -g "$(slurp)" -t png -c - | tee /home/diego/imagenes/capturas/screenshot-$(date +%Y%m%d-%H%M%S).png | wl-copy -t image/png
}

main() {
	if [ "$1" == full ]; then
		full
	elif [ "$1" == geometry ]; then
		geometry
	else
		printf "use: scr <full|geometry>\n"
	fi
}

main "$1"
