#!/bin/bash

full() {
	maim "/home/diego/imagenes/capturas/screenshot-$(date +%Y%m%d-%H%M%S).png"
	xclip -selection clipboard -t image/png "/home/diego/imagenes/capturas/screenshot-$(date +%Y%m%d-%H%M%S).png"
}

geometry() {
	maim -s "/home/diego/imagenes/capturas/screenshot-$(date +%Y%m%d-%H%M%S).png"
	xclip -selection clipboard -t image/png "/home/diego/imagenes/capturas/screenshot-$(date +%Y%m%d-%H%M%S).png"
}

main() {
	if [ "$1" == "full" ]; then
		full
	elif [ "$1" == "geometry" ]; then
		geometry
	else
		printf '\033[32m->\033[m no valid parameter.\n' >&2
		exit 1
	fi
}

main "$1"
