#!/bin/bash
numeros=0

final() {
	printf "Listo! revisa tu archivo.\n"
	exit 0
}

numeros() {
	printf "Modo: Solo numeros. (-N)\n"
	read -p "Introduce el nombre del archivo: " archivo
	read -p "Introduce el numero: " numero

	while true;
	        do
	        if (( $numeros >= $numero )); then
	        final
	        elif (( $numeros < $numero )); then
	        (( numeros += 1 ))
		printf "Linea: $numeros\n"
	        echo $numeros >> $archivo
	fi
done
}

numeropalabra() {
	printf "Modo: Palabras con cabezales de numeros. (-n)\n"
	read -p "Introduce el nombre del archivo: " archivo
	read -p "Introduce el numero: " numero
	read -p "Introduce la palabra: " palabra

	while true;
                do
                if (( $numeros >= $numero )); then
                final
                elif (( $numeros < $numero )); then
                (( numeros += 1 ))
		printf "Linea: $numeros\n"
                echo "$numeros) $palabra" >> $archivo
        fi
done
}

palabras() {
	printf "Modo: Solo palabras. (-p)\n"
        read -p "Introduce el nombre del archivo: " archivo
        read -p "Introduce el numero: " numero
        read -p "Introduce la palabra: " palabra

        while true;
                do
                if (( $numeros >= $numero )); then
                final
                elif (( $numeros < $numero )); then
                (( numeros += 1 ))
		printf "Linea: $numeros\n"
                echo "$palabra" >> $archivo
        fi
done
}

if [[ $1 = -h ]]; then
        printf -- "    -n  pones un numero antes de la palabra\n"
        printf -- "    -N  pones numeros del 1 hasta el numero que pongas\n"
	printf -- "    -p  pones palabras\n"
	exit 0
elif [[ $1 = -n ]]; then
        numeropalabra
elif [[ $1 = -N ]]; then
        numeros
elif [[ $1 = -p ]]; then
        palabras
else
        palabras
fi

