#!/bin/sh
#
# tux - shows tux logo using neofetch/pfetch

err() {
    printf '\033[31m->\033[m %s.\n' "$*" >&2
    exit 1
}

logo() {
	if command -v pfetch >/dev/null 2>&1; then
		PF_INFO="ascii" pfetch
	elif command -v neofetch >/dev/null 2>&1; then
		neofetch --logo
	else
		err neither neofetch or pfetch is installed
	fi
}

main() {
	logo
	clear

	trap "printf '[?25h[?7h\n'" EXIT INT
	printf '[?25l[?7l[2J[H'

	logo

	read -r _
}

main
