#!/bin/sh

user=diego

log() {
    printf '\033[32m->\033[m %s.\n' "$*"
}

err() {
    log "$*" >&2
    exit 1
}

flatpak() {
    log updating flatpak
    su $user -c "flatpak update -y"
    printf "\n"
}

apk() {
    log updating apk
    command apk update
    command apk upgrade
    printf "\n"
}

main() {
    [ "$(id -u)" = 0 ] || err script needs to be run as root
    flatpak || err updating flatpak failed
    apk || err updating apk failed
}

main
