#!/bin/bash

if [ "$1" == up ]; then
	amixer sset Master 5%+
elif [ "$1" == down ]; then
	amixer sset Master 5%-
elif [ "$1" == toggle ]; then
	amixer sset Master toggle
else 
	printf "use: vol <up|down|toggle>\n"
fi
